#! /bin/sh
# /home/pi/git/2017season/GRIP Files/Tracking/GripRunner.py

### BEGIN INIT INFO 
# Provides: 	GripRunner (2017 FRC vision tracking)
# Required-Start:	$remote_fs $syslog
# Required-Stop: 	$remote_fs $syslog 
# Default-Start:	2 3 4 5
# Default-Stop: 	0 1 6
# Short-Description: 	Simple script to start frc vision tracking on boot
# Description: 		A script created by Joe Brooksbank (2017) to start this Raspberry Pi with vision tracking
### END INIT INFO

case "$1" in
  start)
    echo "Starting opencv..."
    # run application you want to start
    /usr/local/bin/GripRunner
    ;;
  stop)
    echo "Stopping opencv..."
    # kill application you want to stop
    killall GripRunner
    ;;
  *)
    echo "Usage: /etc/init.d/GripRunner {start|stop}"
    exit 1
    ;;
esac

exit 0
